site_name: Modelos Probabilísticos de Señales y Sistemas

nav:
  - Inicio: index.md
  - La probabilidad: 
    - Introducción: 1_0_introduccion.md
    - Teoría de conjuntos: 1_1_1_conjuntos.md
    - Análisis combinatorio: 1_1_2_combinatorio.md
  - Variables aleatorias:
    - Introducción: 2_0_introduccion.md
  - Variables aleatorias conjuntas:
    - Introducción: 3_0_introduccion.md
  - Procesos aleatorios:
    - Introducción: 4_0_introduccion.md

theme:
  name: material
  language: es
